spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peekaboo_db
    username: root
    password: Peekaboo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: 12345678901234567890123456789012
  expiration: 900000
  refresh-expiration: 604800000